os: linux
services: docker
dist: focal
language: go
go: 1.16

env:
  global:
  - GOFLAGS: -mod=mod

# Builds routinely fail due to download failures inside alternate arch docker containers
# Here we are downloading outside the docker container and copying the deps in
# Also use -v for downloads/builds to stop no output failures from lxd env buffering.

jobs:
  include:
  - stage: everything
# this runs everything
    script: make ci
# break up ci target so we get faster feedback
  - script: make verify-modules
  - script: make verify
  - script: make all
  - script: make test
  - script: make -f Makefile.prow ci
