name: Bug Report
description: Tell us about a problem you are experiencing
labels: ["kind/bug", "triage/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a Velero bug.

  - type: textarea
    id: what-happened
    attributes:
      label: What steps did you take and what happened
      description: A clear and concise description of what the bug is, and what commands you ran.
      placeholder: Describe the bug and the steps to reproduce it...
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen
      description: Describe what you expected to see.
      placeholder: I expected Velero to...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Support Bundle and Logs
        The following information will help us better understand what's going on

  - type: dropdown
    id: velero-version-check
    attributes:
      label: Velero Version Check
      description: Which version of Velero are you using?
      options:
        - Velero v1.7.0 or newer
        - Earlier version of Velero
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or support bundle
      description: |
        If you are using Velero v1.7.0+:
        Please use `velero debug --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help`

        If you are using earlier versions:
        Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
        - `kubectl logs deployment/velero -n velero`
        - `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
        - `velero backup logs <backupname>`
        - `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
        - `velero restore logs <restorename>`
      render: shell

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else you would like to add
      description: Miscellaneous information that will assist in solving the issue.
      placeholder: Additional context, related issues, possible solutions...

  - type: input
    id: velero-version
    attributes:
      label: Velero version
      description: Use `velero version`
      placeholder: e.g., v1.10.0
    validations:
      required: true

  - type: input
    id: velero-features
    attributes:
      label: Velero features
      description: Use `velero client config get features`
      placeholder: e.g., EnableCSI=true, EnableAPIGroupVersions=true

  - type: input
    id: kubernetes-version
    attributes:
      label: Kubernetes version
      description: Use `kubectl version`
      placeholder: e.g., v1.26.1
    validations:
      required: true

  - type: input
    id: kubernetes-installer
    attributes:
      label: Kubernetes installer & version
      placeholder: e.g., EKS v1.26, kOps 1.25, etc.

  - type: input
    id: cloud-provider
    attributes:
      label: Cloud provider or hardware configuration
      placeholder: e.g., AWS, Azure, GCP, on-premises, etc.

  - type: input
    id: os-version
    attributes:
      label: OS
      description: From `/etc/os-release`
      placeholder: e.g., Ubuntu 22.04, RHEL 8, etc.

  - type: markdown
    attributes:
      value: |
        ## Community Support
        
        If you need help, you can engage with the community in the following places:
        - [Velero Slack channel](https://kubernetes.slack.com/archives/C6VCGP4MT)
        - [Get an invitation to Kubernetes Slack](http://slack.k8s.io/)
        - [GitHub Discussions](https://github.com/vmware-tanzu/velero/discussions)
        
        ## Vote on this issue!
        
        This is an invitation to the Velero community to vote on issues. You can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
        
        Use the "reaction smiley face" up to the right of this comment to vote:
        
        - 👍 for "I would like to see this bug fixed as soon as possible"
        - 👎 for "There are more important bugs to focus on right now"
