name: Question / Support Request
description: Ask a question or request support for using Velero
labels: ["kind/question", "triage/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ Before submitting a question
        
        Please consider using these other resources first:
        
        - Check the [Velero documentation](https://velero.io/docs/)
        - Post in the [Discussions forum](https://github.com/vmware-tanzu/velero/discussions)
        - Ask in the [#velero channel on Kubernetes Slack](https://kubernetes.slack.com/archives/C6VCGP4MT)
        - [Get an invitation to Kubernetes Slack](http://slack.k8s.io/)
        
        If you still need to submit a question as an issue, please proceed.

  - type: textarea
    id: question
    attributes:
      label: What is your question or support request?
      description: A clear and concise description of your question or the support you need.
      placeholder: I'm trying to use Velero for... and I'm wondering how to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, configurations, or environment details relevant to your question.
      placeholder: I've already tried... I'm using Velero in the following way...

  - type: input
    id: velero-version
    attributes:
      label: Velero version
      description: Use `velero version`
      placeholder: e.g., v1.10.0
    validations:
      required: true

  - type: input
    id: velero-features
    attributes:
      label: Velero features
      description: Use `velero client config get features`
      placeholder: e.g., EnableCSI=true, EnableAPIGroupVersions=true

  - type: input
    id: kubernetes-version
    attributes:
      label: Kubernetes version
      description: Use `kubectl version`
      placeholder: e.g., v1.26.1
    validations:
      required: true

  - type: input
    id: kubernetes-installer
    attributes:
      label: Kubernetes installer & version
      placeholder: e.g., EKS v1.26, kOps 1.25, etc.

  - type: input
    id: cloud-provider
    attributes:
      label: Cloud provider or hardware configuration
      placeholder: e.g., AWS, Azure, GCP, on-premises, etc.

  - type: input
    id: os-version
    attributes:
      label: OS
      description: From `/etc/os-release`
      placeholder: e.g., Ubuntu 22.04, RHEL 8, etc.
