name: Main CI

on:
  push:
    branches:
      - 'main'
      - 'release-**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      id: go

    - uses: actions/checkout@v3

    # Fix issue of setup-gcloud
    - run: |
        sudo apt-get install python2.7
        export CLOUDSDK_PYTHON="/usr/bin/python2"

    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '285.0.0'
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Build
      run: |
        make local
        # Clean go cache to ease the build environment storage pressure.
        go clean -modcache -cache

    - name: Test
      run: make test

    - name: Upload test coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        verbose: true

    # Use the JSON key in secret to login gcr.io
    - uses: 'docker/login-action@v1'
      id: gcr-login
      with:
        registry: 'gcr.io' # or REGION.docker.pkg.dev
        username: '_json_key'
        password: '${{ secrets.GCR_SA_KEY }}'
      continue-on-error: true

    # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
    - name: Publish container image to GCR
      if: github.repository == 'vmware-tanzu/velero' && steps.gcr-login.outcome == 'success'
      run: |
        REGISTRY=gcr.io/velero-gcp ./hack/docker-push.sh

    - name: Login to GitHub registry if it's a fork
      if: github.event_name != 'pull_request' && github.repository != 'vmware-tanzu/velero'
      id: ghcr-login
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish container image to GitHub registry if it's a fork
      if: github.event_name != 'pull_request' && github.repository != 'vmware-tanzu/velero' && steps.ghcr-login.outcome == 'success'
      run: |
        REGISTRY=ghcr.io/${{ github.actor }} ./hack/docker-push.sh

